### ISSUE TITLE
패키지 이름 우리 통일 할까? 뭐로 통일하는게 좋을까 의견 남겨줘!

### ISSUE THREAD

**Issue by yoojin-kim** [seoyoonbaek/pbk_My-Note#5]
난 일단 소웨공 이니까 SWE 에다가 2018년에 18  붙여서 SWE18 이라했는뎈ㅋㅋ

**Comment by seoyoonbaek** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋsofteng의 연장선이네
나도 좋아 SWE18!!

**Comment by gonipark** [comment]
softeng 놀리지마요 부드러운 영어가 뭐 어때서 !!!!!!!!!!!!!!!!!!

**Comment by yoojin-kim** [comment]
ㅋㅋㅋㅋ안놀려 안놀려 그럼 SWE18 로 하는거로 하고 이슈 닫을게~~~!
